name: Jim Beckmann
favicon: null
layout_spectrum: 0.6874254243448377
typography_spectrum: 0.39940237859264016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.34955273871310055
  lightness: 0.46645682537928224
  saturation: 0.11616227659396827
  rhythmicContrast: 0.3110769840423018
purpose: []
